/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package tr.com.sakarya.uni.tez.kafka.models;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public enum CRUDType { 
  CREATE, READ, DELETE, UPDATE  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"CRUDType\",\"namespace\":\"tr.com.sakarya.uni.tez.kafka.models\",\"symbols\":[\"CREATE\",\"READ\",\"DELETE\",\"UPDATE\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
}
