/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package tr.com.sakarya.uni.tez.kafka.models;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class Depo extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Depo\",\"namespace\":\"tr.com.sakarya.uni.tez.kafka.models\",\"fields\":[{\"name\":\"depo_adi\",\"type\":[\"null\",\"string\"]},{\"name\":\"depo_id\",\"type\":\"int\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public java.lang.CharSequence depo_adi;
  @Deprecated public int depo_id;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>. 
   */
  public Depo() {}

  /**
   * All-args constructor.
   */
  public Depo(java.lang.CharSequence depo_adi, java.lang.Integer depo_id) {
    this.depo_adi = depo_adi;
    this.depo_id = depo_id;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return depo_adi;
    case 1: return depo_id;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: depo_adi = (java.lang.CharSequence)value$; break;
    case 1: depo_id = (java.lang.Integer)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'depo_adi' field.
   */
  public java.lang.CharSequence getDepoAdi() {
    return depo_adi;
  }

  /**
   * Sets the value of the 'depo_adi' field.
   * @param value the value to set.
   */
  public void setDepoAdi(java.lang.CharSequence value) {
    this.depo_adi = value;
  }

  /**
   * Gets the value of the 'depo_id' field.
   */
  public java.lang.Integer getDepoId() {
    return depo_id;
  }

  /**
   * Sets the value of the 'depo_id' field.
   * @param value the value to set.
   */
  public void setDepoId(java.lang.Integer value) {
    this.depo_id = value;
  }

  /** Creates a new Depo RecordBuilder */
  public static tr.com.sakarya.uni.tez.kafka.models.Depo.Builder newBuilder() {
    return new tr.com.sakarya.uni.tez.kafka.models.Depo.Builder();
  }
  
  /** Creates a new Depo RecordBuilder by copying an existing Builder */
  public static tr.com.sakarya.uni.tez.kafka.models.Depo.Builder newBuilder(tr.com.sakarya.uni.tez.kafka.models.Depo.Builder other) {
    return new tr.com.sakarya.uni.tez.kafka.models.Depo.Builder(other);
  }
  
  /** Creates a new Depo RecordBuilder by copying an existing Depo instance */
  public static tr.com.sakarya.uni.tez.kafka.models.Depo.Builder newBuilder(tr.com.sakarya.uni.tez.kafka.models.Depo other) {
    return new tr.com.sakarya.uni.tez.kafka.models.Depo.Builder(other);
  }
  
  /**
   * RecordBuilder for Depo instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Depo>
    implements org.apache.avro.data.RecordBuilder<Depo> {

    private java.lang.CharSequence depo_adi;
    private int depo_id;

    /** Creates a new Builder */
    private Builder() {
      super(tr.com.sakarya.uni.tez.kafka.models.Depo.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(tr.com.sakarya.uni.tez.kafka.models.Depo.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.depo_adi)) {
        this.depo_adi = data().deepCopy(fields()[0].schema(), other.depo_adi);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.depo_id)) {
        this.depo_id = data().deepCopy(fields()[1].schema(), other.depo_id);
        fieldSetFlags()[1] = true;
      }
    }
    
    /** Creates a Builder by copying an existing Depo instance */
    private Builder(tr.com.sakarya.uni.tez.kafka.models.Depo other) {
            super(tr.com.sakarya.uni.tez.kafka.models.Depo.SCHEMA$);
      if (isValidValue(fields()[0], other.depo_adi)) {
        this.depo_adi = data().deepCopy(fields()[0].schema(), other.depo_adi);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.depo_id)) {
        this.depo_id = data().deepCopy(fields()[1].schema(), other.depo_id);
        fieldSetFlags()[1] = true;
      }
    }

    /** Gets the value of the 'depo_adi' field */
    public java.lang.CharSequence getDepoAdi() {
      return depo_adi;
    }
    
    /** Sets the value of the 'depo_adi' field */
    public tr.com.sakarya.uni.tez.kafka.models.Depo.Builder setDepoAdi(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.depo_adi = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the 'depo_adi' field has been set */
    public boolean hasDepoAdi() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the 'depo_adi' field */
    public tr.com.sakarya.uni.tez.kafka.models.Depo.Builder clearDepoAdi() {
      depo_adi = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /** Gets the value of the 'depo_id' field */
    public java.lang.Integer getDepoId() {
      return depo_id;
    }
    
    /** Sets the value of the 'depo_id' field */
    public tr.com.sakarya.uni.tez.kafka.models.Depo.Builder setDepoId(int value) {
      validate(fields()[1], value);
      this.depo_id = value;
      fieldSetFlags()[1] = true;
      return this; 
    }
    
    /** Checks whether the 'depo_id' field has been set */
    public boolean hasDepoId() {
      return fieldSetFlags()[1];
    }
    
    /** Clears the value of the 'depo_id' field */
    public tr.com.sakarya.uni.tez.kafka.models.Depo.Builder clearDepoId() {
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    public Depo build() {
      try {
        Depo record = new Depo();
        record.depo_adi = fieldSetFlags()[0] ? this.depo_adi : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.depo_id = fieldSetFlags()[1] ? this.depo_id : (java.lang.Integer) defaultValue(fields()[1]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
