/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package tr.com.sakarya.uni.tez.kafka.models;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class DKProductInfoTable extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"DKProductInfoTable\",\"namespace\":\"tr.com.sakarya.uni.tez.kafka.models\",\"fields\":[{\"name\":\"productInfoTable\",\"type\":[\"null\",{\"type\":\"array\",\"items\":{\"type\":\"record\",\"name\":\"DKProductInfo\",\"fields\":[{\"name\":\"depoAdi\",\"type\":[\"null\",\"string\"]},{\"name\":\"depoId\",\"type\":\"int\"},{\"name\":\"markaAdi\",\"type\":[\"null\",\"string\"]},{\"name\":\"markaId\",\"type\":\"int\"},{\"name\":\"urunAdi\",\"type\":[\"null\",\"string\"]},{\"name\":\"urunId\",\"type\":\"int\"},{\"name\":\"urunTurAdi\",\"type\":[\"null\",\"string\"]},{\"name\":\"urunTurId\",\"type\":\"int\"}]}}]}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public java.util.List<tr.com.sakarya.uni.tez.kafka.models.DKProductInfo> productInfoTable;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>. 
   */
  public DKProductInfoTable() {}

  /**
   * All-args constructor.
   */
  public DKProductInfoTable(java.util.List<tr.com.sakarya.uni.tez.kafka.models.DKProductInfo> productInfoTable) {
    this.productInfoTable = productInfoTable;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return productInfoTable;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: productInfoTable = (java.util.List<tr.com.sakarya.uni.tez.kafka.models.DKProductInfo>)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'productInfoTable' field.
   */
  public java.util.List<tr.com.sakarya.uni.tez.kafka.models.DKProductInfo> getProductInfoTable() {
    return productInfoTable;
  }

  /**
   * Sets the value of the 'productInfoTable' field.
   * @param value the value to set.
   */
  public void setProductInfoTable(java.util.List<tr.com.sakarya.uni.tez.kafka.models.DKProductInfo> value) {
    this.productInfoTable = value;
  }

  /** Creates a new DKProductInfoTable RecordBuilder */
  public static tr.com.sakarya.uni.tez.kafka.models.DKProductInfoTable.Builder newBuilder() {
    return new tr.com.sakarya.uni.tez.kafka.models.DKProductInfoTable.Builder();
  }
  
  /** Creates a new DKProductInfoTable RecordBuilder by copying an existing Builder */
  public static tr.com.sakarya.uni.tez.kafka.models.DKProductInfoTable.Builder newBuilder(tr.com.sakarya.uni.tez.kafka.models.DKProductInfoTable.Builder other) {
    return new tr.com.sakarya.uni.tez.kafka.models.DKProductInfoTable.Builder(other);
  }
  
  /** Creates a new DKProductInfoTable RecordBuilder by copying an existing DKProductInfoTable instance */
  public static tr.com.sakarya.uni.tez.kafka.models.DKProductInfoTable.Builder newBuilder(tr.com.sakarya.uni.tez.kafka.models.DKProductInfoTable other) {
    return new tr.com.sakarya.uni.tez.kafka.models.DKProductInfoTable.Builder(other);
  }
  
  /**
   * RecordBuilder for DKProductInfoTable instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<DKProductInfoTable>
    implements org.apache.avro.data.RecordBuilder<DKProductInfoTable> {

    private java.util.List<tr.com.sakarya.uni.tez.kafka.models.DKProductInfo> productInfoTable;

    /** Creates a new Builder */
    private Builder() {
      super(tr.com.sakarya.uni.tez.kafka.models.DKProductInfoTable.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(tr.com.sakarya.uni.tez.kafka.models.DKProductInfoTable.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.productInfoTable)) {
        this.productInfoTable = data().deepCopy(fields()[0].schema(), other.productInfoTable);
        fieldSetFlags()[0] = true;
      }
    }
    
    /** Creates a Builder by copying an existing DKProductInfoTable instance */
    private Builder(tr.com.sakarya.uni.tez.kafka.models.DKProductInfoTable other) {
            super(tr.com.sakarya.uni.tez.kafka.models.DKProductInfoTable.SCHEMA$);
      if (isValidValue(fields()[0], other.productInfoTable)) {
        this.productInfoTable = data().deepCopy(fields()[0].schema(), other.productInfoTable);
        fieldSetFlags()[0] = true;
      }
    }

    /** Gets the value of the 'productInfoTable' field */
    public java.util.List<tr.com.sakarya.uni.tez.kafka.models.DKProductInfo> getProductInfoTable() {
      return productInfoTable;
    }
    
    /** Sets the value of the 'productInfoTable' field */
    public tr.com.sakarya.uni.tez.kafka.models.DKProductInfoTable.Builder setProductInfoTable(java.util.List<tr.com.sakarya.uni.tez.kafka.models.DKProductInfo> value) {
      validate(fields()[0], value);
      this.productInfoTable = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the 'productInfoTable' field has been set */
    public boolean hasProductInfoTable() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the 'productInfoTable' field */
    public tr.com.sakarya.uni.tez.kafka.models.DKProductInfoTable.Builder clearProductInfoTable() {
      productInfoTable = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    @Override
    public DKProductInfoTable build() {
      try {
        DKProductInfoTable record = new DKProductInfoTable();
        record.productInfoTable = fieldSetFlags()[0] ? this.productInfoTable : (java.util.List<tr.com.sakarya.uni.tez.kafka.models.DKProductInfo>) defaultValue(fields()[0]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
