/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package tr.com.siparis.sistemi.kafka.model;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class SiparisKafkaModel extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"SiparisKafkaModel\",\"namespace\":\"tr.com.siparis.sistemi.kafka.model\",\"fields\":[{\"name\":\"siparisListesi\",\"type\":[\"null\",{\"type\":\"array\",\"items\":{\"type\":\"record\",\"name\":\"Siparis\",\"fields\":[{\"name\":\"anayemekAdi\",\"type\":[\"null\",\"string\"]},{\"name\":\"anayemekId\",\"type\":\"int\"},{\"name\":\"corbaAdi\",\"type\":[\"null\",\"string\"]},{\"name\":\"corbaId\",\"type\":\"int\"},{\"name\":\"kullaniciAdi\",\"type\":[\"null\",\"string\"]},{\"name\":\"kullaniciId\",\"type\":\"int\"},{\"name\":\"kullaniciSoyadi\",\"type\":[\"null\",\"string\"]},{\"name\":\"kullaniciTurAdi\",\"type\":[\"null\",\"string\"]},{\"name\":\"kullaniciTurId\",\"type\":\"int\"},{\"name\":\"masaAdi\",\"type\":[\"null\",\"string\"]},{\"name\":\"masaId\",\"type\":\"int\"},{\"name\":\"salataAdi\",\"type\":[\"null\",\"string\"]},{\"name\":\"salataId\",\"type\":\"int\"},{\"name\":\"siparisDurumu\",\"type\":[\"null\",\"string\"]},{\"name\":\"siparisId\",\"type\":\"int\"},{\"name\":\"tatliAdi\",\"type\":[\"null\",\"string\"]},{\"name\":\"tatliId\",\"type\":\"int\"}]}}]}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public java.util.List<tr.com.siparis.sistemi.kafka.model.Siparis> siparisListesi;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>. 
   */
  public SiparisKafkaModel() {}

  /**
   * All-args constructor.
   */
  public SiparisKafkaModel(java.util.List<tr.com.siparis.sistemi.kafka.model.Siparis> siparisListesi) {
    this.siparisListesi = siparisListesi;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return siparisListesi;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: siparisListesi = (java.util.List<tr.com.siparis.sistemi.kafka.model.Siparis>)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'siparisListesi' field.
   */
  public java.util.List<tr.com.siparis.sistemi.kafka.model.Siparis> getSiparisListesi() {
    return siparisListesi;
  }

  /**
   * Sets the value of the 'siparisListesi' field.
   * @param value the value to set.
   */
  public void setSiparisListesi(java.util.List<tr.com.siparis.sistemi.kafka.model.Siparis> value) {
    this.siparisListesi = value;
  }

  /** Creates a new SiparisKafkaModel RecordBuilder */
  public static tr.com.siparis.sistemi.kafka.model.SiparisKafkaModel.Builder newBuilder() {
    return new tr.com.siparis.sistemi.kafka.model.SiparisKafkaModel.Builder();
  }
  
  /** Creates a new SiparisKafkaModel RecordBuilder by copying an existing Builder */
  public static tr.com.siparis.sistemi.kafka.model.SiparisKafkaModel.Builder newBuilder(tr.com.siparis.sistemi.kafka.model.SiparisKafkaModel.Builder other) {
    return new tr.com.siparis.sistemi.kafka.model.SiparisKafkaModel.Builder(other);
  }
  
  /** Creates a new SiparisKafkaModel RecordBuilder by copying an existing SiparisKafkaModel instance */
  public static tr.com.siparis.sistemi.kafka.model.SiparisKafkaModel.Builder newBuilder(tr.com.siparis.sistemi.kafka.model.SiparisKafkaModel other) {
    return new tr.com.siparis.sistemi.kafka.model.SiparisKafkaModel.Builder(other);
  }
  
  /**
   * RecordBuilder for SiparisKafkaModel instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<SiparisKafkaModel>
    implements org.apache.avro.data.RecordBuilder<SiparisKafkaModel> {

    private java.util.List<tr.com.siparis.sistemi.kafka.model.Siparis> siparisListesi;

    /** Creates a new Builder */
    private Builder() {
      super(tr.com.siparis.sistemi.kafka.model.SiparisKafkaModel.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(tr.com.siparis.sistemi.kafka.model.SiparisKafkaModel.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.siparisListesi)) {
        this.siparisListesi = data().deepCopy(fields()[0].schema(), other.siparisListesi);
        fieldSetFlags()[0] = true;
      }
    }
    
    /** Creates a Builder by copying an existing SiparisKafkaModel instance */
    private Builder(tr.com.siparis.sistemi.kafka.model.SiparisKafkaModel other) {
            super(tr.com.siparis.sistemi.kafka.model.SiparisKafkaModel.SCHEMA$);
      if (isValidValue(fields()[0], other.siparisListesi)) {
        this.siparisListesi = data().deepCopy(fields()[0].schema(), other.siparisListesi);
        fieldSetFlags()[0] = true;
      }
    }

    /** Gets the value of the 'siparisListesi' field */
    public java.util.List<tr.com.siparis.sistemi.kafka.model.Siparis> getSiparisListesi() {
      return siparisListesi;
    }
    
    /** Sets the value of the 'siparisListesi' field */
    public tr.com.siparis.sistemi.kafka.model.SiparisKafkaModel.Builder setSiparisListesi(java.util.List<tr.com.siparis.sistemi.kafka.model.Siparis> value) {
      validate(fields()[0], value);
      this.siparisListesi = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the 'siparisListesi' field has been set */
    public boolean hasSiparisListesi() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the 'siparisListesi' field */
    public tr.com.siparis.sistemi.kafka.model.SiparisKafkaModel.Builder clearSiparisListesi() {
      siparisListesi = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    @Override
    public SiparisKafkaModel build() {
      try {
        SiparisKafkaModel record = new SiparisKafkaModel();
        record.siparisListesi = fieldSetFlags()[0] ? this.siparisListesi : (java.util.List<tr.com.siparis.sistemi.kafka.model.Siparis>) defaultValue(fields()[0]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
