/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package tr.com.siparis.sistemi.kafka.model;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class Siparis extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Siparis\",\"namespace\":\"tr.com.siparis.sistemi.kafka.model\",\"fields\":[{\"name\":\"anayemekAdi\",\"type\":[\"null\",\"string\"]},{\"name\":\"anayemekId\",\"type\":\"int\"},{\"name\":\"corbaAdi\",\"type\":[\"null\",\"string\"]},{\"name\":\"corbaId\",\"type\":\"int\"},{\"name\":\"kullaniciAdi\",\"type\":[\"null\",\"string\"]},{\"name\":\"kullaniciId\",\"type\":\"int\"},{\"name\":\"kullaniciSoyadi\",\"type\":[\"null\",\"string\"]},{\"name\":\"kullaniciTurAdi\",\"type\":[\"null\",\"string\"]},{\"name\":\"kullaniciTurId\",\"type\":\"int\"},{\"name\":\"masaAdi\",\"type\":[\"null\",\"string\"]},{\"name\":\"masaId\",\"type\":\"int\"},{\"name\":\"salataAdi\",\"type\":[\"null\",\"string\"]},{\"name\":\"salataId\",\"type\":\"int\"},{\"name\":\"siparisDurumu\",\"type\":[\"null\",\"string\"]},{\"name\":\"siparisId\",\"type\":\"int\"},{\"name\":\"tatliAdi\",\"type\":[\"null\",\"string\"]},{\"name\":\"tatliId\",\"type\":\"int\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public java.lang.CharSequence anayemekAdi;
  @Deprecated public int anayemekId;
  @Deprecated public java.lang.CharSequence corbaAdi;
  @Deprecated public int corbaId;
  @Deprecated public java.lang.CharSequence kullaniciAdi;
  @Deprecated public int kullaniciId;
  @Deprecated public java.lang.CharSequence kullaniciSoyadi;
  @Deprecated public java.lang.CharSequence kullaniciTurAdi;
  @Deprecated public int kullaniciTurId;
  @Deprecated public java.lang.CharSequence masaAdi;
  @Deprecated public int masaId;
  @Deprecated public java.lang.CharSequence salataAdi;
  @Deprecated public int salataId;
  @Deprecated public java.lang.CharSequence siparisDurumu;
  @Deprecated public int siparisId;
  @Deprecated public java.lang.CharSequence tatliAdi;
  @Deprecated public int tatliId;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>. 
   */
  public Siparis() {}

  /**
   * All-args constructor.
   */
  public Siparis(java.lang.CharSequence anayemekAdi, java.lang.Integer anayemekId, java.lang.CharSequence corbaAdi, java.lang.Integer corbaId, java.lang.CharSequence kullaniciAdi, java.lang.Integer kullaniciId, java.lang.CharSequence kullaniciSoyadi, java.lang.CharSequence kullaniciTurAdi, java.lang.Integer kullaniciTurId, java.lang.CharSequence masaAdi, java.lang.Integer masaId, java.lang.CharSequence salataAdi, java.lang.Integer salataId, java.lang.CharSequence siparisDurumu, java.lang.Integer siparisId, java.lang.CharSequence tatliAdi, java.lang.Integer tatliId) {
    this.anayemekAdi = anayemekAdi;
    this.anayemekId = anayemekId;
    this.corbaAdi = corbaAdi;
    this.corbaId = corbaId;
    this.kullaniciAdi = kullaniciAdi;
    this.kullaniciId = kullaniciId;
    this.kullaniciSoyadi = kullaniciSoyadi;
    this.kullaniciTurAdi = kullaniciTurAdi;
    this.kullaniciTurId = kullaniciTurId;
    this.masaAdi = masaAdi;
    this.masaId = masaId;
    this.salataAdi = salataAdi;
    this.salataId = salataId;
    this.siparisDurumu = siparisDurumu;
    this.siparisId = siparisId;
    this.tatliAdi = tatliAdi;
    this.tatliId = tatliId;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return anayemekAdi;
    case 1: return anayemekId;
    case 2: return corbaAdi;
    case 3: return corbaId;
    case 4: return kullaniciAdi;
    case 5: return kullaniciId;
    case 6: return kullaniciSoyadi;
    case 7: return kullaniciTurAdi;
    case 8: return kullaniciTurId;
    case 9: return masaAdi;
    case 10: return masaId;
    case 11: return salataAdi;
    case 12: return salataId;
    case 13: return siparisDurumu;
    case 14: return siparisId;
    case 15: return tatliAdi;
    case 16: return tatliId;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: anayemekAdi = (java.lang.CharSequence)value$; break;
    case 1: anayemekId = (java.lang.Integer)value$; break;
    case 2: corbaAdi = (java.lang.CharSequence)value$; break;
    case 3: corbaId = (java.lang.Integer)value$; break;
    case 4: kullaniciAdi = (java.lang.CharSequence)value$; break;
    case 5: kullaniciId = (java.lang.Integer)value$; break;
    case 6: kullaniciSoyadi = (java.lang.CharSequence)value$; break;
    case 7: kullaniciTurAdi = (java.lang.CharSequence)value$; break;
    case 8: kullaniciTurId = (java.lang.Integer)value$; break;
    case 9: masaAdi = (java.lang.CharSequence)value$; break;
    case 10: masaId = (java.lang.Integer)value$; break;
    case 11: salataAdi = (java.lang.CharSequence)value$; break;
    case 12: salataId = (java.lang.Integer)value$; break;
    case 13: siparisDurumu = (java.lang.CharSequence)value$; break;
    case 14: siparisId = (java.lang.Integer)value$; break;
    case 15: tatliAdi = (java.lang.CharSequence)value$; break;
    case 16: tatliId = (java.lang.Integer)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'anayemekAdi' field.
   */
  public java.lang.CharSequence getAnayemekAdi() {
    return anayemekAdi;
  }

  /**
   * Sets the value of the 'anayemekAdi' field.
   * @param value the value to set.
   */
  public void setAnayemekAdi(java.lang.CharSequence value) {
    this.anayemekAdi = value;
  }

  /**
   * Gets the value of the 'anayemekId' field.
   */
  public java.lang.Integer getAnayemekId() {
    return anayemekId;
  }

  /**
   * Sets the value of the 'anayemekId' field.
   * @param value the value to set.
   */
  public void setAnayemekId(java.lang.Integer value) {
    this.anayemekId = value;
  }

  /**
   * Gets the value of the 'corbaAdi' field.
   */
  public java.lang.CharSequence getCorbaAdi() {
    return corbaAdi;
  }

  /**
   * Sets the value of the 'corbaAdi' field.
   * @param value the value to set.
   */
  public void setCorbaAdi(java.lang.CharSequence value) {
    this.corbaAdi = value;
  }

  /**
   * Gets the value of the 'corbaId' field.
   */
  public java.lang.Integer getCorbaId() {
    return corbaId;
  }

  /**
   * Sets the value of the 'corbaId' field.
   * @param value the value to set.
   */
  public void setCorbaId(java.lang.Integer value) {
    this.corbaId = value;
  }

  /**
   * Gets the value of the 'kullaniciAdi' field.
   */
  public java.lang.CharSequence getKullaniciAdi() {
    return kullaniciAdi;
  }

  /**
   * Sets the value of the 'kullaniciAdi' field.
   * @param value the value to set.
   */
  public void setKullaniciAdi(java.lang.CharSequence value) {
    this.kullaniciAdi = value;
  }

  /**
   * Gets the value of the 'kullaniciId' field.
   */
  public java.lang.Integer getKullaniciId() {
    return kullaniciId;
  }

  /**
   * Sets the value of the 'kullaniciId' field.
   * @param value the value to set.
   */
  public void setKullaniciId(java.lang.Integer value) {
    this.kullaniciId = value;
  }

  /**
   * Gets the value of the 'kullaniciSoyadi' field.
   */
  public java.lang.CharSequence getKullaniciSoyadi() {
    return kullaniciSoyadi;
  }

  /**
   * Sets the value of the 'kullaniciSoyadi' field.
   * @param value the value to set.
   */
  public void setKullaniciSoyadi(java.lang.CharSequence value) {
    this.kullaniciSoyadi = value;
  }

  /**
   * Gets the value of the 'kullaniciTurAdi' field.
   */
  public java.lang.CharSequence getKullaniciTurAdi() {
    return kullaniciTurAdi;
  }

  /**
   * Sets the value of the 'kullaniciTurAdi' field.
   * @param value the value to set.
   */
  public void setKullaniciTurAdi(java.lang.CharSequence value) {
    this.kullaniciTurAdi = value;
  }

  /**
   * Gets the value of the 'kullaniciTurId' field.
   */
  public java.lang.Integer getKullaniciTurId() {
    return kullaniciTurId;
  }

  /**
   * Sets the value of the 'kullaniciTurId' field.
   * @param value the value to set.
   */
  public void setKullaniciTurId(java.lang.Integer value) {
    this.kullaniciTurId = value;
  }

  /**
   * Gets the value of the 'masaAdi' field.
   */
  public java.lang.CharSequence getMasaAdi() {
    return masaAdi;
  }

  /**
   * Sets the value of the 'masaAdi' field.
   * @param value the value to set.
   */
  public void setMasaAdi(java.lang.CharSequence value) {
    this.masaAdi = value;
  }

  /**
   * Gets the value of the 'masaId' field.
   */
  public java.lang.Integer getMasaId() {
    return masaId;
  }

  /**
   * Sets the value of the 'masaId' field.
   * @param value the value to set.
   */
  public void setMasaId(java.lang.Integer value) {
    this.masaId = value;
  }

  /**
   * Gets the value of the 'salataAdi' field.
   */
  public java.lang.CharSequence getSalataAdi() {
    return salataAdi;
  }

  /**
   * Sets the value of the 'salataAdi' field.
   * @param value the value to set.
   */
  public void setSalataAdi(java.lang.CharSequence value) {
    this.salataAdi = value;
  }

  /**
   * Gets the value of the 'salataId' field.
   */
  public java.lang.Integer getSalataId() {
    return salataId;
  }

  /**
   * Sets the value of the 'salataId' field.
   * @param value the value to set.
   */
  public void setSalataId(java.lang.Integer value) {
    this.salataId = value;
  }

  /**
   * Gets the value of the 'siparisDurumu' field.
   */
  public java.lang.CharSequence getSiparisDurumu() {
    return siparisDurumu;
  }

  /**
   * Sets the value of the 'siparisDurumu' field.
   * @param value the value to set.
   */
  public void setSiparisDurumu(java.lang.CharSequence value) {
    this.siparisDurumu = value;
  }

  /**
   * Gets the value of the 'siparisId' field.
   */
  public java.lang.Integer getSiparisId() {
    return siparisId;
  }

  /**
   * Sets the value of the 'siparisId' field.
   * @param value the value to set.
   */
  public void setSiparisId(java.lang.Integer value) {
    this.siparisId = value;
  }

  /**
   * Gets the value of the 'tatliAdi' field.
   */
  public java.lang.CharSequence getTatliAdi() {
    return tatliAdi;
  }

  /**
   * Sets the value of the 'tatliAdi' field.
   * @param value the value to set.
   */
  public void setTatliAdi(java.lang.CharSequence value) {
    this.tatliAdi = value;
  }

  /**
   * Gets the value of the 'tatliId' field.
   */
  public java.lang.Integer getTatliId() {
    return tatliId;
  }

  /**
   * Sets the value of the 'tatliId' field.
   * @param value the value to set.
   */
  public void setTatliId(java.lang.Integer value) {
    this.tatliId = value;
  }

  /** Creates a new Siparis RecordBuilder */
  public static tr.com.siparis.sistemi.kafka.model.Siparis.Builder newBuilder() {
    return new tr.com.siparis.sistemi.kafka.model.Siparis.Builder();
  }
  
  /** Creates a new Siparis RecordBuilder by copying an existing Builder */
  public static tr.com.siparis.sistemi.kafka.model.Siparis.Builder newBuilder(tr.com.siparis.sistemi.kafka.model.Siparis.Builder other) {
    return new tr.com.siparis.sistemi.kafka.model.Siparis.Builder(other);
  }
  
  /** Creates a new Siparis RecordBuilder by copying an existing Siparis instance */
  public static tr.com.siparis.sistemi.kafka.model.Siparis.Builder newBuilder(tr.com.siparis.sistemi.kafka.model.Siparis other) {
    return new tr.com.siparis.sistemi.kafka.model.Siparis.Builder(other);
  }
  
  /**
   * RecordBuilder for Siparis instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Siparis>
    implements org.apache.avro.data.RecordBuilder<Siparis> {

    private java.lang.CharSequence anayemekAdi;
    private int anayemekId;
    private java.lang.CharSequence corbaAdi;
    private int corbaId;
    private java.lang.CharSequence kullaniciAdi;
    private int kullaniciId;
    private java.lang.CharSequence kullaniciSoyadi;
    private java.lang.CharSequence kullaniciTurAdi;
    private int kullaniciTurId;
    private java.lang.CharSequence masaAdi;
    private int masaId;
    private java.lang.CharSequence salataAdi;
    private int salataId;
    private java.lang.CharSequence siparisDurumu;
    private int siparisId;
    private java.lang.CharSequence tatliAdi;
    private int tatliId;

    /** Creates a new Builder */
    private Builder() {
      super(tr.com.siparis.sistemi.kafka.model.Siparis.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(tr.com.siparis.sistemi.kafka.model.Siparis.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.anayemekAdi)) {
        this.anayemekAdi = data().deepCopy(fields()[0].schema(), other.anayemekAdi);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.anayemekId)) {
        this.anayemekId = data().deepCopy(fields()[1].schema(), other.anayemekId);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.corbaAdi)) {
        this.corbaAdi = data().deepCopy(fields()[2].schema(), other.corbaAdi);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.corbaId)) {
        this.corbaId = data().deepCopy(fields()[3].schema(), other.corbaId);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.kullaniciAdi)) {
        this.kullaniciAdi = data().deepCopy(fields()[4].schema(), other.kullaniciAdi);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.kullaniciId)) {
        this.kullaniciId = data().deepCopy(fields()[5].schema(), other.kullaniciId);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.kullaniciSoyadi)) {
        this.kullaniciSoyadi = data().deepCopy(fields()[6].schema(), other.kullaniciSoyadi);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.kullaniciTurAdi)) {
        this.kullaniciTurAdi = data().deepCopy(fields()[7].schema(), other.kullaniciTurAdi);
        fieldSetFlags()[7] = true;
      }
      if (isValidValue(fields()[8], other.kullaniciTurId)) {
        this.kullaniciTurId = data().deepCopy(fields()[8].schema(), other.kullaniciTurId);
        fieldSetFlags()[8] = true;
      }
      if (isValidValue(fields()[9], other.masaAdi)) {
        this.masaAdi = data().deepCopy(fields()[9].schema(), other.masaAdi);
        fieldSetFlags()[9] = true;
      }
      if (isValidValue(fields()[10], other.masaId)) {
        this.masaId = data().deepCopy(fields()[10].schema(), other.masaId);
        fieldSetFlags()[10] = true;
      }
      if (isValidValue(fields()[11], other.salataAdi)) {
        this.salataAdi = data().deepCopy(fields()[11].schema(), other.salataAdi);
        fieldSetFlags()[11] = true;
      }
      if (isValidValue(fields()[12], other.salataId)) {
        this.salataId = data().deepCopy(fields()[12].schema(), other.salataId);
        fieldSetFlags()[12] = true;
      }
      if (isValidValue(fields()[13], other.siparisDurumu)) {
        this.siparisDurumu = data().deepCopy(fields()[13].schema(), other.siparisDurumu);
        fieldSetFlags()[13] = true;
      }
      if (isValidValue(fields()[14], other.siparisId)) {
        this.siparisId = data().deepCopy(fields()[14].schema(), other.siparisId);
        fieldSetFlags()[14] = true;
      }
      if (isValidValue(fields()[15], other.tatliAdi)) {
        this.tatliAdi = data().deepCopy(fields()[15].schema(), other.tatliAdi);
        fieldSetFlags()[15] = true;
      }
      if (isValidValue(fields()[16], other.tatliId)) {
        this.tatliId = data().deepCopy(fields()[16].schema(), other.tatliId);
        fieldSetFlags()[16] = true;
      }
    }
    
    /** Creates a Builder by copying an existing Siparis instance */
    private Builder(tr.com.siparis.sistemi.kafka.model.Siparis other) {
            super(tr.com.siparis.sistemi.kafka.model.Siparis.SCHEMA$);
      if (isValidValue(fields()[0], other.anayemekAdi)) {
        this.anayemekAdi = data().deepCopy(fields()[0].schema(), other.anayemekAdi);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.anayemekId)) {
        this.anayemekId = data().deepCopy(fields()[1].schema(), other.anayemekId);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.corbaAdi)) {
        this.corbaAdi = data().deepCopy(fields()[2].schema(), other.corbaAdi);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.corbaId)) {
        this.corbaId = data().deepCopy(fields()[3].schema(), other.corbaId);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.kullaniciAdi)) {
        this.kullaniciAdi = data().deepCopy(fields()[4].schema(), other.kullaniciAdi);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.kullaniciId)) {
        this.kullaniciId = data().deepCopy(fields()[5].schema(), other.kullaniciId);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.kullaniciSoyadi)) {
        this.kullaniciSoyadi = data().deepCopy(fields()[6].schema(), other.kullaniciSoyadi);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.kullaniciTurAdi)) {
        this.kullaniciTurAdi = data().deepCopy(fields()[7].schema(), other.kullaniciTurAdi);
        fieldSetFlags()[7] = true;
      }
      if (isValidValue(fields()[8], other.kullaniciTurId)) {
        this.kullaniciTurId = data().deepCopy(fields()[8].schema(), other.kullaniciTurId);
        fieldSetFlags()[8] = true;
      }
      if (isValidValue(fields()[9], other.masaAdi)) {
        this.masaAdi = data().deepCopy(fields()[9].schema(), other.masaAdi);
        fieldSetFlags()[9] = true;
      }
      if (isValidValue(fields()[10], other.masaId)) {
        this.masaId = data().deepCopy(fields()[10].schema(), other.masaId);
        fieldSetFlags()[10] = true;
      }
      if (isValidValue(fields()[11], other.salataAdi)) {
        this.salataAdi = data().deepCopy(fields()[11].schema(), other.salataAdi);
        fieldSetFlags()[11] = true;
      }
      if (isValidValue(fields()[12], other.salataId)) {
        this.salataId = data().deepCopy(fields()[12].schema(), other.salataId);
        fieldSetFlags()[12] = true;
      }
      if (isValidValue(fields()[13], other.siparisDurumu)) {
        this.siparisDurumu = data().deepCopy(fields()[13].schema(), other.siparisDurumu);
        fieldSetFlags()[13] = true;
      }
      if (isValidValue(fields()[14], other.siparisId)) {
        this.siparisId = data().deepCopy(fields()[14].schema(), other.siparisId);
        fieldSetFlags()[14] = true;
      }
      if (isValidValue(fields()[15], other.tatliAdi)) {
        this.tatliAdi = data().deepCopy(fields()[15].schema(), other.tatliAdi);
        fieldSetFlags()[15] = true;
      }
      if (isValidValue(fields()[16], other.tatliId)) {
        this.tatliId = data().deepCopy(fields()[16].schema(), other.tatliId);
        fieldSetFlags()[16] = true;
      }
    }

    /** Gets the value of the 'anayemekAdi' field */
    public java.lang.CharSequence getAnayemekAdi() {
      return anayemekAdi;
    }
    
    /** Sets the value of the 'anayemekAdi' field */
    public tr.com.siparis.sistemi.kafka.model.Siparis.Builder setAnayemekAdi(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.anayemekAdi = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the 'anayemekAdi' field has been set */
    public boolean hasAnayemekAdi() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the 'anayemekAdi' field */
    public tr.com.siparis.sistemi.kafka.model.Siparis.Builder clearAnayemekAdi() {
      anayemekAdi = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /** Gets the value of the 'anayemekId' field */
    public java.lang.Integer getAnayemekId() {
      return anayemekId;
    }
    
    /** Sets the value of the 'anayemekId' field */
    public tr.com.siparis.sistemi.kafka.model.Siparis.Builder setAnayemekId(int value) {
      validate(fields()[1], value);
      this.anayemekId = value;
      fieldSetFlags()[1] = true;
      return this; 
    }
    
    /** Checks whether the 'anayemekId' field has been set */
    public boolean hasAnayemekId() {
      return fieldSetFlags()[1];
    }
    
    /** Clears the value of the 'anayemekId' field */
    public tr.com.siparis.sistemi.kafka.model.Siparis.Builder clearAnayemekId() {
      fieldSetFlags()[1] = false;
      return this;
    }

    /** Gets the value of the 'corbaAdi' field */
    public java.lang.CharSequence getCorbaAdi() {
      return corbaAdi;
    }
    
    /** Sets the value of the 'corbaAdi' field */
    public tr.com.siparis.sistemi.kafka.model.Siparis.Builder setCorbaAdi(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.corbaAdi = value;
      fieldSetFlags()[2] = true;
      return this; 
    }
    
    /** Checks whether the 'corbaAdi' field has been set */
    public boolean hasCorbaAdi() {
      return fieldSetFlags()[2];
    }
    
    /** Clears the value of the 'corbaAdi' field */
    public tr.com.siparis.sistemi.kafka.model.Siparis.Builder clearCorbaAdi() {
      corbaAdi = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /** Gets the value of the 'corbaId' field */
    public java.lang.Integer getCorbaId() {
      return corbaId;
    }
    
    /** Sets the value of the 'corbaId' field */
    public tr.com.siparis.sistemi.kafka.model.Siparis.Builder setCorbaId(int value) {
      validate(fields()[3], value);
      this.corbaId = value;
      fieldSetFlags()[3] = true;
      return this; 
    }
    
    /** Checks whether the 'corbaId' field has been set */
    public boolean hasCorbaId() {
      return fieldSetFlags()[3];
    }
    
    /** Clears the value of the 'corbaId' field */
    public tr.com.siparis.sistemi.kafka.model.Siparis.Builder clearCorbaId() {
      fieldSetFlags()[3] = false;
      return this;
    }

    /** Gets the value of the 'kullaniciAdi' field */
    public java.lang.CharSequence getKullaniciAdi() {
      return kullaniciAdi;
    }
    
    /** Sets the value of the 'kullaniciAdi' field */
    public tr.com.siparis.sistemi.kafka.model.Siparis.Builder setKullaniciAdi(java.lang.CharSequence value) {
      validate(fields()[4], value);
      this.kullaniciAdi = value;
      fieldSetFlags()[4] = true;
      return this; 
    }
    
    /** Checks whether the 'kullaniciAdi' field has been set */
    public boolean hasKullaniciAdi() {
      return fieldSetFlags()[4];
    }
    
    /** Clears the value of the 'kullaniciAdi' field */
    public tr.com.siparis.sistemi.kafka.model.Siparis.Builder clearKullaniciAdi() {
      kullaniciAdi = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    /** Gets the value of the 'kullaniciId' field */
    public java.lang.Integer getKullaniciId() {
      return kullaniciId;
    }
    
    /** Sets the value of the 'kullaniciId' field */
    public tr.com.siparis.sistemi.kafka.model.Siparis.Builder setKullaniciId(int value) {
      validate(fields()[5], value);
      this.kullaniciId = value;
      fieldSetFlags()[5] = true;
      return this; 
    }
    
    /** Checks whether the 'kullaniciId' field has been set */
    public boolean hasKullaniciId() {
      return fieldSetFlags()[5];
    }
    
    /** Clears the value of the 'kullaniciId' field */
    public tr.com.siparis.sistemi.kafka.model.Siparis.Builder clearKullaniciId() {
      fieldSetFlags()[5] = false;
      return this;
    }

    /** Gets the value of the 'kullaniciSoyadi' field */
    public java.lang.CharSequence getKullaniciSoyadi() {
      return kullaniciSoyadi;
    }
    
    /** Sets the value of the 'kullaniciSoyadi' field */
    public tr.com.siparis.sistemi.kafka.model.Siparis.Builder setKullaniciSoyadi(java.lang.CharSequence value) {
      validate(fields()[6], value);
      this.kullaniciSoyadi = value;
      fieldSetFlags()[6] = true;
      return this; 
    }
    
    /** Checks whether the 'kullaniciSoyadi' field has been set */
    public boolean hasKullaniciSoyadi() {
      return fieldSetFlags()[6];
    }
    
    /** Clears the value of the 'kullaniciSoyadi' field */
    public tr.com.siparis.sistemi.kafka.model.Siparis.Builder clearKullaniciSoyadi() {
      kullaniciSoyadi = null;
      fieldSetFlags()[6] = false;
      return this;
    }

    /** Gets the value of the 'kullaniciTurAdi' field */
    public java.lang.CharSequence getKullaniciTurAdi() {
      return kullaniciTurAdi;
    }
    
    /** Sets the value of the 'kullaniciTurAdi' field */
    public tr.com.siparis.sistemi.kafka.model.Siparis.Builder setKullaniciTurAdi(java.lang.CharSequence value) {
      validate(fields()[7], value);
      this.kullaniciTurAdi = value;
      fieldSetFlags()[7] = true;
      return this; 
    }
    
    /** Checks whether the 'kullaniciTurAdi' field has been set */
    public boolean hasKullaniciTurAdi() {
      return fieldSetFlags()[7];
    }
    
    /** Clears the value of the 'kullaniciTurAdi' field */
    public tr.com.siparis.sistemi.kafka.model.Siparis.Builder clearKullaniciTurAdi() {
      kullaniciTurAdi = null;
      fieldSetFlags()[7] = false;
      return this;
    }

    /** Gets the value of the 'kullaniciTurId' field */
    public java.lang.Integer getKullaniciTurId() {
      return kullaniciTurId;
    }
    
    /** Sets the value of the 'kullaniciTurId' field */
    public tr.com.siparis.sistemi.kafka.model.Siparis.Builder setKullaniciTurId(int value) {
      validate(fields()[8], value);
      this.kullaniciTurId = value;
      fieldSetFlags()[8] = true;
      return this; 
    }
    
    /** Checks whether the 'kullaniciTurId' field has been set */
    public boolean hasKullaniciTurId() {
      return fieldSetFlags()[8];
    }
    
    /** Clears the value of the 'kullaniciTurId' field */
    public tr.com.siparis.sistemi.kafka.model.Siparis.Builder clearKullaniciTurId() {
      fieldSetFlags()[8] = false;
      return this;
    }

    /** Gets the value of the 'masaAdi' field */
    public java.lang.CharSequence getMasaAdi() {
      return masaAdi;
    }
    
    /** Sets the value of the 'masaAdi' field */
    public tr.com.siparis.sistemi.kafka.model.Siparis.Builder setMasaAdi(java.lang.CharSequence value) {
      validate(fields()[9], value);
      this.masaAdi = value;
      fieldSetFlags()[9] = true;
      return this; 
    }
    
    /** Checks whether the 'masaAdi' field has been set */
    public boolean hasMasaAdi() {
      return fieldSetFlags()[9];
    }
    
    /** Clears the value of the 'masaAdi' field */
    public tr.com.siparis.sistemi.kafka.model.Siparis.Builder clearMasaAdi() {
      masaAdi = null;
      fieldSetFlags()[9] = false;
      return this;
    }

    /** Gets the value of the 'masaId' field */
    public java.lang.Integer getMasaId() {
      return masaId;
    }
    
    /** Sets the value of the 'masaId' field */
    public tr.com.siparis.sistemi.kafka.model.Siparis.Builder setMasaId(int value) {
      validate(fields()[10], value);
      this.masaId = value;
      fieldSetFlags()[10] = true;
      return this; 
    }
    
    /** Checks whether the 'masaId' field has been set */
    public boolean hasMasaId() {
      return fieldSetFlags()[10];
    }
    
    /** Clears the value of the 'masaId' field */
    public tr.com.siparis.sistemi.kafka.model.Siparis.Builder clearMasaId() {
      fieldSetFlags()[10] = false;
      return this;
    }

    /** Gets the value of the 'salataAdi' field */
    public java.lang.CharSequence getSalataAdi() {
      return salataAdi;
    }
    
    /** Sets the value of the 'salataAdi' field */
    public tr.com.siparis.sistemi.kafka.model.Siparis.Builder setSalataAdi(java.lang.CharSequence value) {
      validate(fields()[11], value);
      this.salataAdi = value;
      fieldSetFlags()[11] = true;
      return this; 
    }
    
    /** Checks whether the 'salataAdi' field has been set */
    public boolean hasSalataAdi() {
      return fieldSetFlags()[11];
    }
    
    /** Clears the value of the 'salataAdi' field */
    public tr.com.siparis.sistemi.kafka.model.Siparis.Builder clearSalataAdi() {
      salataAdi = null;
      fieldSetFlags()[11] = false;
      return this;
    }

    /** Gets the value of the 'salataId' field */
    public java.lang.Integer getSalataId() {
      return salataId;
    }
    
    /** Sets the value of the 'salataId' field */
    public tr.com.siparis.sistemi.kafka.model.Siparis.Builder setSalataId(int value) {
      validate(fields()[12], value);
      this.salataId = value;
      fieldSetFlags()[12] = true;
      return this; 
    }
    
    /** Checks whether the 'salataId' field has been set */
    public boolean hasSalataId() {
      return fieldSetFlags()[12];
    }
    
    /** Clears the value of the 'salataId' field */
    public tr.com.siparis.sistemi.kafka.model.Siparis.Builder clearSalataId() {
      fieldSetFlags()[12] = false;
      return this;
    }

    /** Gets the value of the 'siparisDurumu' field */
    public java.lang.CharSequence getSiparisDurumu() {
      return siparisDurumu;
    }
    
    /** Sets the value of the 'siparisDurumu' field */
    public tr.com.siparis.sistemi.kafka.model.Siparis.Builder setSiparisDurumu(java.lang.CharSequence value) {
      validate(fields()[13], value);
      this.siparisDurumu = value;
      fieldSetFlags()[13] = true;
      return this; 
    }
    
    /** Checks whether the 'siparisDurumu' field has been set */
    public boolean hasSiparisDurumu() {
      return fieldSetFlags()[13];
    }
    
    /** Clears the value of the 'siparisDurumu' field */
    public tr.com.siparis.sistemi.kafka.model.Siparis.Builder clearSiparisDurumu() {
      siparisDurumu = null;
      fieldSetFlags()[13] = false;
      return this;
    }

    /** Gets the value of the 'siparisId' field */
    public java.lang.Integer getSiparisId() {
      return siparisId;
    }
    
    /** Sets the value of the 'siparisId' field */
    public tr.com.siparis.sistemi.kafka.model.Siparis.Builder setSiparisId(int value) {
      validate(fields()[14], value);
      this.siparisId = value;
      fieldSetFlags()[14] = true;
      return this; 
    }
    
    /** Checks whether the 'siparisId' field has been set */
    public boolean hasSiparisId() {
      return fieldSetFlags()[14];
    }
    
    /** Clears the value of the 'siparisId' field */
    public tr.com.siparis.sistemi.kafka.model.Siparis.Builder clearSiparisId() {
      fieldSetFlags()[14] = false;
      return this;
    }

    /** Gets the value of the 'tatliAdi' field */
    public java.lang.CharSequence getTatliAdi() {
      return tatliAdi;
    }
    
    /** Sets the value of the 'tatliAdi' field */
    public tr.com.siparis.sistemi.kafka.model.Siparis.Builder setTatliAdi(java.lang.CharSequence value) {
      validate(fields()[15], value);
      this.tatliAdi = value;
      fieldSetFlags()[15] = true;
      return this; 
    }
    
    /** Checks whether the 'tatliAdi' field has been set */
    public boolean hasTatliAdi() {
      return fieldSetFlags()[15];
    }
    
    /** Clears the value of the 'tatliAdi' field */
    public tr.com.siparis.sistemi.kafka.model.Siparis.Builder clearTatliAdi() {
      tatliAdi = null;
      fieldSetFlags()[15] = false;
      return this;
    }

    /** Gets the value of the 'tatliId' field */
    public java.lang.Integer getTatliId() {
      return tatliId;
    }
    
    /** Sets the value of the 'tatliId' field */
    public tr.com.siparis.sistemi.kafka.model.Siparis.Builder setTatliId(int value) {
      validate(fields()[16], value);
      this.tatliId = value;
      fieldSetFlags()[16] = true;
      return this; 
    }
    
    /** Checks whether the 'tatliId' field has been set */
    public boolean hasTatliId() {
      return fieldSetFlags()[16];
    }
    
    /** Clears the value of the 'tatliId' field */
    public tr.com.siparis.sistemi.kafka.model.Siparis.Builder clearTatliId() {
      fieldSetFlags()[16] = false;
      return this;
    }

    @Override
    public Siparis build() {
      try {
        Siparis record = new Siparis();
        record.anayemekAdi = fieldSetFlags()[0] ? this.anayemekAdi : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.anayemekId = fieldSetFlags()[1] ? this.anayemekId : (java.lang.Integer) defaultValue(fields()[1]);
        record.corbaAdi = fieldSetFlags()[2] ? this.corbaAdi : (java.lang.CharSequence) defaultValue(fields()[2]);
        record.corbaId = fieldSetFlags()[3] ? this.corbaId : (java.lang.Integer) defaultValue(fields()[3]);
        record.kullaniciAdi = fieldSetFlags()[4] ? this.kullaniciAdi : (java.lang.CharSequence) defaultValue(fields()[4]);
        record.kullaniciId = fieldSetFlags()[5] ? this.kullaniciId : (java.lang.Integer) defaultValue(fields()[5]);
        record.kullaniciSoyadi = fieldSetFlags()[6] ? this.kullaniciSoyadi : (java.lang.CharSequence) defaultValue(fields()[6]);
        record.kullaniciTurAdi = fieldSetFlags()[7] ? this.kullaniciTurAdi : (java.lang.CharSequence) defaultValue(fields()[7]);
        record.kullaniciTurId = fieldSetFlags()[8] ? this.kullaniciTurId : (java.lang.Integer) defaultValue(fields()[8]);
        record.masaAdi = fieldSetFlags()[9] ? this.masaAdi : (java.lang.CharSequence) defaultValue(fields()[9]);
        record.masaId = fieldSetFlags()[10] ? this.masaId : (java.lang.Integer) defaultValue(fields()[10]);
        record.salataAdi = fieldSetFlags()[11] ? this.salataAdi : (java.lang.CharSequence) defaultValue(fields()[11]);
        record.salataId = fieldSetFlags()[12] ? this.salataId : (java.lang.Integer) defaultValue(fields()[12]);
        record.siparisDurumu = fieldSetFlags()[13] ? this.siparisDurumu : (java.lang.CharSequence) defaultValue(fields()[13]);
        record.siparisId = fieldSetFlags()[14] ? this.siparisId : (java.lang.Integer) defaultValue(fields()[14]);
        record.tatliAdi = fieldSetFlags()[15] ? this.tatliAdi : (java.lang.CharSequence) defaultValue(fields()[15]);
        record.tatliId = fieldSetFlags()[16] ? this.tatliId : (java.lang.Integer) defaultValue(fields()[16]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
