/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package tr.com.siparis.sistemi.kafka.model;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class TatliKafkaModel extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"TatliKafkaModel\",\"namespace\":\"tr.com.siparis.sistemi.kafka.model\",\"fields\":[{\"name\":\"tatliListesi\",\"type\":[\"null\",{\"type\":\"array\",\"items\":{\"type\":\"record\",\"name\":\"Tatli\",\"fields\":[{\"name\":\"tatliAdi\",\"type\":[\"null\",\"string\"]},{\"name\":\"tatliId\",\"type\":\"int\"}]}}]}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public java.util.List<tr.com.siparis.sistemi.kafka.model.Tatli> tatliListesi;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>. 
   */
  public TatliKafkaModel() {}

  /**
   * All-args constructor.
   */
  public TatliKafkaModel(java.util.List<tr.com.siparis.sistemi.kafka.model.Tatli> tatliListesi) {
    this.tatliListesi = tatliListesi;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return tatliListesi;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: tatliListesi = (java.util.List<tr.com.siparis.sistemi.kafka.model.Tatli>)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'tatliListesi' field.
   */
  public java.util.List<tr.com.siparis.sistemi.kafka.model.Tatli> getTatliListesi() {
    return tatliListesi;
  }

  /**
   * Sets the value of the 'tatliListesi' field.
   * @param value the value to set.
   */
  public void setTatliListesi(java.util.List<tr.com.siparis.sistemi.kafka.model.Tatli> value) {
    this.tatliListesi = value;
  }

  /** Creates a new TatliKafkaModel RecordBuilder */
  public static tr.com.siparis.sistemi.kafka.model.TatliKafkaModel.Builder newBuilder() {
    return new tr.com.siparis.sistemi.kafka.model.TatliKafkaModel.Builder();
  }
  
  /** Creates a new TatliKafkaModel RecordBuilder by copying an existing Builder */
  public static tr.com.siparis.sistemi.kafka.model.TatliKafkaModel.Builder newBuilder(tr.com.siparis.sistemi.kafka.model.TatliKafkaModel.Builder other) {
    return new tr.com.siparis.sistemi.kafka.model.TatliKafkaModel.Builder(other);
  }
  
  /** Creates a new TatliKafkaModel RecordBuilder by copying an existing TatliKafkaModel instance */
  public static tr.com.siparis.sistemi.kafka.model.TatliKafkaModel.Builder newBuilder(tr.com.siparis.sistemi.kafka.model.TatliKafkaModel other) {
    return new tr.com.siparis.sistemi.kafka.model.TatliKafkaModel.Builder(other);
  }
  
  /**
   * RecordBuilder for TatliKafkaModel instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<TatliKafkaModel>
    implements org.apache.avro.data.RecordBuilder<TatliKafkaModel> {

    private java.util.List<tr.com.siparis.sistemi.kafka.model.Tatli> tatliListesi;

    /** Creates a new Builder */
    private Builder() {
      super(tr.com.siparis.sistemi.kafka.model.TatliKafkaModel.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(tr.com.siparis.sistemi.kafka.model.TatliKafkaModel.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.tatliListesi)) {
        this.tatliListesi = data().deepCopy(fields()[0].schema(), other.tatliListesi);
        fieldSetFlags()[0] = true;
      }
    }
    
    /** Creates a Builder by copying an existing TatliKafkaModel instance */
    private Builder(tr.com.siparis.sistemi.kafka.model.TatliKafkaModel other) {
            super(tr.com.siparis.sistemi.kafka.model.TatliKafkaModel.SCHEMA$);
      if (isValidValue(fields()[0], other.tatliListesi)) {
        this.tatliListesi = data().deepCopy(fields()[0].schema(), other.tatliListesi);
        fieldSetFlags()[0] = true;
      }
    }

    /** Gets the value of the 'tatliListesi' field */
    public java.util.List<tr.com.siparis.sistemi.kafka.model.Tatli> getTatliListesi() {
      return tatliListesi;
    }
    
    /** Sets the value of the 'tatliListesi' field */
    public tr.com.siparis.sistemi.kafka.model.TatliKafkaModel.Builder setTatliListesi(java.util.List<tr.com.siparis.sistemi.kafka.model.Tatli> value) {
      validate(fields()[0], value);
      this.tatliListesi = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the 'tatliListesi' field has been set */
    public boolean hasTatliListesi() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the 'tatliListesi' field */
    public tr.com.siparis.sistemi.kafka.model.TatliKafkaModel.Builder clearTatliListesi() {
      tatliListesi = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    @Override
    public TatliKafkaModel build() {
      try {
        TatliKafkaModel record = new TatliKafkaModel();
        record.tatliListesi = fieldSetFlags()[0] ? this.tatliListesi : (java.util.List<tr.com.siparis.sistemi.kafka.model.Tatli>) defaultValue(fields()[0]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
