/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package tr.com.siparis.sistemi.kafka.model;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class AnayemekKafkaModel extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"AnayemekKafkaModel\",\"namespace\":\"tr.com.siparis.sistemi.kafka.model\",\"fields\":[{\"name\":\"anayemekListesi\",\"type\":[\"null\",{\"type\":\"array\",\"items\":{\"type\":\"record\",\"name\":\"Anayemek\",\"fields\":[{\"name\":\"anayemek\",\"type\":[\"null\",\"string\"]},{\"name\":\"anayemekId\",\"type\":\"int\"}]}}]}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public java.util.List<tr.com.siparis.sistemi.kafka.model.Anayemek> anayemekListesi;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>. 
   */
  public AnayemekKafkaModel() {}

  /**
   * All-args constructor.
   */
  public AnayemekKafkaModel(java.util.List<tr.com.siparis.sistemi.kafka.model.Anayemek> anayemekListesi) {
    this.anayemekListesi = anayemekListesi;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return anayemekListesi;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: anayemekListesi = (java.util.List<tr.com.siparis.sistemi.kafka.model.Anayemek>)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'anayemekListesi' field.
   */
  public java.util.List<tr.com.siparis.sistemi.kafka.model.Anayemek> getAnayemekListesi() {
    return anayemekListesi;
  }

  /**
   * Sets the value of the 'anayemekListesi' field.
   * @param value the value to set.
   */
  public void setAnayemekListesi(java.util.List<tr.com.siparis.sistemi.kafka.model.Anayemek> value) {
    this.anayemekListesi = value;
  }

  /** Creates a new AnayemekKafkaModel RecordBuilder */
  public static tr.com.siparis.sistemi.kafka.model.AnayemekKafkaModel.Builder newBuilder() {
    return new tr.com.siparis.sistemi.kafka.model.AnayemekKafkaModel.Builder();
  }
  
  /** Creates a new AnayemekKafkaModel RecordBuilder by copying an existing Builder */
  public static tr.com.siparis.sistemi.kafka.model.AnayemekKafkaModel.Builder newBuilder(tr.com.siparis.sistemi.kafka.model.AnayemekKafkaModel.Builder other) {
    return new tr.com.siparis.sistemi.kafka.model.AnayemekKafkaModel.Builder(other);
  }
  
  /** Creates a new AnayemekKafkaModel RecordBuilder by copying an existing AnayemekKafkaModel instance */
  public static tr.com.siparis.sistemi.kafka.model.AnayemekKafkaModel.Builder newBuilder(tr.com.siparis.sistemi.kafka.model.AnayemekKafkaModel other) {
    return new tr.com.siparis.sistemi.kafka.model.AnayemekKafkaModel.Builder(other);
  }
  
  /**
   * RecordBuilder for AnayemekKafkaModel instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<AnayemekKafkaModel>
    implements org.apache.avro.data.RecordBuilder<AnayemekKafkaModel> {

    private java.util.List<tr.com.siparis.sistemi.kafka.model.Anayemek> anayemekListesi;

    /** Creates a new Builder */
    private Builder() {
      super(tr.com.siparis.sistemi.kafka.model.AnayemekKafkaModel.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(tr.com.siparis.sistemi.kafka.model.AnayemekKafkaModel.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.anayemekListesi)) {
        this.anayemekListesi = data().deepCopy(fields()[0].schema(), other.anayemekListesi);
        fieldSetFlags()[0] = true;
      }
    }
    
    /** Creates a Builder by copying an existing AnayemekKafkaModel instance */
    private Builder(tr.com.siparis.sistemi.kafka.model.AnayemekKafkaModel other) {
            super(tr.com.siparis.sistemi.kafka.model.AnayemekKafkaModel.SCHEMA$);
      if (isValidValue(fields()[0], other.anayemekListesi)) {
        this.anayemekListesi = data().deepCopy(fields()[0].schema(), other.anayemekListesi);
        fieldSetFlags()[0] = true;
      }
    }

    /** Gets the value of the 'anayemekListesi' field */
    public java.util.List<tr.com.siparis.sistemi.kafka.model.Anayemek> getAnayemekListesi() {
      return anayemekListesi;
    }
    
    /** Sets the value of the 'anayemekListesi' field */
    public tr.com.siparis.sistemi.kafka.model.AnayemekKafkaModel.Builder setAnayemekListesi(java.util.List<tr.com.siparis.sistemi.kafka.model.Anayemek> value) {
      validate(fields()[0], value);
      this.anayemekListesi = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the 'anayemekListesi' field has been set */
    public boolean hasAnayemekListesi() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the 'anayemekListesi' field */
    public tr.com.siparis.sistemi.kafka.model.AnayemekKafkaModel.Builder clearAnayemekListesi() {
      anayemekListesi = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    @Override
    public AnayemekKafkaModel build() {
      try {
        AnayemekKafkaModel record = new AnayemekKafkaModel();
        record.anayemekListesi = fieldSetFlags()[0] ? this.anayemekListesi : (java.util.List<tr.com.siparis.sistemi.kafka.model.Anayemek>) defaultValue(fields()[0]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
