/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package tr.com.siparis.sistemi.kafka.model;  
@SuppressWarnings("all")
/**  */
@org.apache.avro.specific.AvroGenerated
public enum CRUDType { 
  CREATE, READ, UPDATE, DELETE  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"CRUDType\",\"namespace\":\"tr.com.siparis.sistemi.kafka.model\",\"doc\":\"\",\"symbols\":[\"CREATE\",\"READ\",\"UPDATE\",\"DELETE\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
}
