/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package tr.com.siparis.sistemi.kafka.model;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class MasaKafkaModel extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"MasaKafkaModel\",\"namespace\":\"tr.com.siparis.sistemi.kafka.model\",\"fields\":[{\"name\":\"masaListesi\",\"type\":[\"null\",{\"type\":\"array\",\"items\":{\"type\":\"record\",\"name\":\"Masa\",\"fields\":[{\"name\":\"masaAdi\",\"type\":[\"null\",\"string\"]},{\"name\":\"masaId\",\"type\":\"int\"}]}}]}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public java.util.List<tr.com.siparis.sistemi.kafka.model.Masa> masaListesi;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>. 
   */
  public MasaKafkaModel() {}

  /**
   * All-args constructor.
   */
  public MasaKafkaModel(java.util.List<tr.com.siparis.sistemi.kafka.model.Masa> masaListesi) {
    this.masaListesi = masaListesi;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return masaListesi;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: masaListesi = (java.util.List<tr.com.siparis.sistemi.kafka.model.Masa>)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'masaListesi' field.
   */
  public java.util.List<tr.com.siparis.sistemi.kafka.model.Masa> getMasaListesi() {
    return masaListesi;
  }

  /**
   * Sets the value of the 'masaListesi' field.
   * @param value the value to set.
   */
  public void setMasaListesi(java.util.List<tr.com.siparis.sistemi.kafka.model.Masa> value) {
    this.masaListesi = value;
  }

  /** Creates a new MasaKafkaModel RecordBuilder */
  public static tr.com.siparis.sistemi.kafka.model.MasaKafkaModel.Builder newBuilder() {
    return new tr.com.siparis.sistemi.kafka.model.MasaKafkaModel.Builder();
  }
  
  /** Creates a new MasaKafkaModel RecordBuilder by copying an existing Builder */
  public static tr.com.siparis.sistemi.kafka.model.MasaKafkaModel.Builder newBuilder(tr.com.siparis.sistemi.kafka.model.MasaKafkaModel.Builder other) {
    return new tr.com.siparis.sistemi.kafka.model.MasaKafkaModel.Builder(other);
  }
  
  /** Creates a new MasaKafkaModel RecordBuilder by copying an existing MasaKafkaModel instance */
  public static tr.com.siparis.sistemi.kafka.model.MasaKafkaModel.Builder newBuilder(tr.com.siparis.sistemi.kafka.model.MasaKafkaModel other) {
    return new tr.com.siparis.sistemi.kafka.model.MasaKafkaModel.Builder(other);
  }
  
  /**
   * RecordBuilder for MasaKafkaModel instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<MasaKafkaModel>
    implements org.apache.avro.data.RecordBuilder<MasaKafkaModel> {

    private java.util.List<tr.com.siparis.sistemi.kafka.model.Masa> masaListesi;

    /** Creates a new Builder */
    private Builder() {
      super(tr.com.siparis.sistemi.kafka.model.MasaKafkaModel.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(tr.com.siparis.sistemi.kafka.model.MasaKafkaModel.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.masaListesi)) {
        this.masaListesi = data().deepCopy(fields()[0].schema(), other.masaListesi);
        fieldSetFlags()[0] = true;
      }
    }
    
    /** Creates a Builder by copying an existing MasaKafkaModel instance */
    private Builder(tr.com.siparis.sistemi.kafka.model.MasaKafkaModel other) {
            super(tr.com.siparis.sistemi.kafka.model.MasaKafkaModel.SCHEMA$);
      if (isValidValue(fields()[0], other.masaListesi)) {
        this.masaListesi = data().deepCopy(fields()[0].schema(), other.masaListesi);
        fieldSetFlags()[0] = true;
      }
    }

    /** Gets the value of the 'masaListesi' field */
    public java.util.List<tr.com.siparis.sistemi.kafka.model.Masa> getMasaListesi() {
      return masaListesi;
    }
    
    /** Sets the value of the 'masaListesi' field */
    public tr.com.siparis.sistemi.kafka.model.MasaKafkaModel.Builder setMasaListesi(java.util.List<tr.com.siparis.sistemi.kafka.model.Masa> value) {
      validate(fields()[0], value);
      this.masaListesi = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the 'masaListesi' field has been set */
    public boolean hasMasaListesi() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the 'masaListesi' field */
    public tr.com.siparis.sistemi.kafka.model.MasaKafkaModel.Builder clearMasaListesi() {
      masaListesi = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    @Override
    public MasaKafkaModel build() {
      try {
        MasaKafkaModel record = new MasaKafkaModel();
        record.masaListesi = fieldSetFlags()[0] ? this.masaListesi : (java.util.List<tr.com.siparis.sistemi.kafka.model.Masa>) defaultValue(fields()[0]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
